
import React from 'react';

export const Terms: React.FC = () => {
  return (
    <div className="pt-32 pb-24 px-4 max-w-4xl mx-auto animate-fade-in text-gray-700 dark:text-gray-300">
      <h1 className="text-4xl font-black text-indigo-950 dark:text-white mb-8">Terms of Service</h1>
      <div className="prose prose-indigo dark:prose-invert max-w-none space-y-6 text-lg leading-relaxed">
        <p>By applying for the Vocademy Beta, you agree to the following terms:</p>
        
        <h2 className="text-2xl font-bold text-indigo-900 dark:text-indigo-400 mt-8">1. Beta Participation</h2>
        <p>Vocademy is currently in a pre-release state. Features may be added, removed, or modified at any time. We do not guarantee 100% uptime during this phase.</p>

        <h2 className="text-2xl font-bold text-indigo-900 dark:text-indigo-400 mt-8">2. Intellectual Property</h2>
        <p>All content generated by our AI models and the application interface is the property of Vocademy. You may use it for personal study but not for commercial redistribution.</p>

        <h2 className="text-2xl font-bold text-indigo-900 dark:text-indigo-400 mt-8">3. Conduct</h2>
        <p>Multiplayer duels and community forums must be used respectfully. Any form of cheating or harassment will result in immediate termination of beta access.</p>

        <h2 className="text-2xl font-bold text-indigo-900 dark:text-indigo-400 mt-8">4. Liability</h2>
        <p>Vocademy provides educational tools. While we strive for accuracy using advanced AI, we are not responsible for errors in definitions or how they might affect your exam performance.</p>
      </div>
    </div>
  );
};
